segre_test:
    jal x1, jmp_1
    li x1, 0xcacacaca
jmp_1:
    jal x2, jmp_2
    li x2, 0xcacacaca
jmp_2:
    jal x3, jmp_3
    li x3, 0xcacacaca
jmp_3:
    jal x4, jmp_4
    li x4, 0xcacacaca
jmp_4:
    jal x5, jmp_5
    li x5, 0xcacacaca
jmp_5:
    jal x6, jmp_6
    li x6, 0xcacacaca
jmp_6:
    jal x7, jmp_7
    li x7, 0xcacacaca
jmp_7:
    jal x8, jmp_8
    li x8, 0xcacacaca
jmp_8:
    jal x9, jmp_9
    li x9, 0xcacacaca
jmp_9:
    jal x10, jmp_10
    li x10, 0xcacacaca
jmp_10:
    jal x11, jmp_11
    li x11, 0xcacacaca
jmp_11:
    jal x12, jmp_12
    li x12, 0xcacacaca
jmp_12:
    jal x13, jmp_13
    li x13, 0xcacacaca
jmp_13:
    jal x14, jmp_14
    li x14, 0xcacacaca
jmp_14:
    jal x15, jmp_15
    li x15, 0xcacacaca
jmp_15:
    jal x16, jmp_16
    li x16, 0xcacacaca
jmp_16:
    jal x17, jmp_17
    li x17, 0xcacacaca
jmp_17:
    jal x18, jmp_18
    li x18, 0xcacacaca
jmp_18:
    jal x19, jmp_19
    li x19, 0xcacacaca
jmp_19:
    jal x20, jmp_20
    li x20, 0xcacacaca
jmp_20:
    jal x21, jmp_21
    li x21, 0xcacacaca
jmp_21:
    jal x22, jmp_22
    li x22, 0xcacacaca
jmp_22:
    jal x23, jmp_23
    li x23, 0xcacacaca
jmp_23:
    jal x24, jmp_24
    li x24, 0xcacacaca
jmp_24:
    jal x25, jmp_25
    li x25, 0xcacacaca
jmp_25:
    jal x26, jmp_26
    li x26, 0xcacacaca
jmp_26:
    jal x27, jmp_27
    li x27, 0xcacacaca
jmp_27:
    jal x28, jmp_28
    li x28, 0xcacacaca
jmp_28:
    jal x29, jmp_29
    li x29, 0xcacacaca
jmp_29:
    jal x30, jmp_30
    li x30, 0xcacacaca
jmp_30:
    jal x31, jmp_31
    li x31, 0xcacacaca
jmp_31:
