segre_test:
    la x1, jmp_1
    jalr x1, 0(x1)
    li x0, 0xcacacaca
jmp_1:
    la x2, jmp_2
    jalr x2, 0(x2)
    li x2, 0xcacacaca
jmp_2:
    la x3, jmp_3
    jalr x3, 0(x3)
    li x3, 0xcacacaca
jmp_3:
    la x4, jmp_4
    jalr x4, 0(x4)
    li x4, 0xcacacaca
jmp_4:
    la x5, jmp_5
    jalr x5, 0(x5)
    li x5, 0xcacacaca
jmp_5:
    la x6, jmp_6
    jalr x6, 0(x6)
    li x6, 0xcacacaca
jmp_6:
    la x7, jmp_7
    jalr x7, 0(x7)
    li x7, 0xcacacaca
jmp_7:
    la x8, jmp_8
    jalr x8, 0(x8)
    li x8, 0xcacacaca
jmp_8:
    la x9, jmp_9
    jalr x9, 0(x9)
    li x9, 0xcacacaca
jmp_9:
    la x10, jmp_10
    jalr x10, 0(x10)
    li x10, 0xcacacaca
jmp_10:
    la x11, jmp_11
    jalr x11, 0(x11)
    li x11, 0xcacacaca
jmp_11:
    la x12, jmp_12
    jalr x12, 0(x12)
    li x12, 0xcacacaca
jmp_12:
    la x13, jmp_13
    jalr x13, 0(x13)
    li x13, 0xcacacaca
jmp_13:
    la x14, jmp_14
    jalr x14, 0(x14)
    li x14, 0xcacacaca
jmp_14:
    la x15, jmp_15
    jalr x15, 0(x15)
    li x15, 0xcacacaca
jmp_15:
    la x16, jmp_16
    jalr x16, 0(x16)
    li x16, 0xcacacaca
jmp_16:
    la x17, jmp_17
    jalr x17, 0(x17)
    li x17, 0xcacacaca
jmp_17:
    la x18, jmp_18
    jalr x18, 0(x18)
    li x18, 0xcacacaca
jmp_18:
    la x19, jmp_19
    jalr x19, 0(x19)
    li x19, 0xcacacaca
jmp_19:
    la x20, jmp_20
    jalr x20, 0(x20)
    li x20, 0xcacacaca
jmp_20:
    la x21, jmp_21
    jalr x21, 0(x21)
    li x21, 0xcacacaca
jmp_21:
    la x22, jmp_22
    jalr x22, 0(x22)
    li x22, 0xcacacaca
jmp_22:
    la x23, jmp_23
    jalr x23, 0(x23)
    li x23, 0xcacacaca
jmp_23:
    la x24, jmp_24
    jalr x24, 0(x24)
    li x24, 0xcacacaca
jmp_24:
    la x25, jmp_25
    jalr x25, 0(x25)
    li x25, 0xcacacaca
jmp_25:
    la x26, jmp_26
    jalr x26, 0(x26)
    li x26, 0xcacacaca
jmp_26:
    la x27, jmp_27
    jalr x27, 0(x27)
    li x27, 0xcacacaca
jmp_27:
    la x28, jmp_28
    jalr x28, 0(x28)
    li x28, 0xcacacaca
jmp_28:
    la x29, jmp_29
    jalr x29, 0(x29)
    li x29, 0xcacacaca
jmp_29:
    la x30, jmp_30
    jalr x30, 0(x30)
    li x30, 0xcacacaca
jmp_30:
    la x31, jmp_31
    jalr x31, 0(x31)
    li x31, 0xcacacaca
jmp_31:
