segre_test:
    li x1,  0x1f
    li x2,  0x10
    li x3,  0xbeefbeef
    li x4,  0xbeefbeef
    li x5,  0xbeefbeef
    li x6,  0xbeefbeef
    li x7,  0xbeefbeef
    li x8,  0xbeefbeef
    li x9,  0xbeefbeef
    li x10, 0xbeefbeef
    li x11, 0xbeefbeef
    li x12, 0xbeefbeef
    li x13, 0xbeefbeef
    li x14, 0xbeefbeef
    li x15, 0xbeefbeef
    li x16, 0xbeefbeef
    li x17, 0xbeefbeef
    li x18, 0xbeefbeef
    li x19, 0xbeefbeef
    li x20, 0xbeefbeef
    li x21, 0xbeefbeef
    li x22, 0xbeefbeef
    li x23, 0xbeefbeef
    li x24, 0xbeefbeef
    li x25, 0xbeefbeef
    li x26, 0xbeefbeef
    li x27, 0xbeefbeef
    li x28, 0xbeefbeef
    li x29, 0xbeefbeef
    li x30, 0xbeefbeef
    li x31, 0xbeefbeef
    sll x0, x1, x1
    sll x2, x2, x2
    sll x3, x3, x1
    sll x4, x4, x2
    sll x5, x5, x1
    sll x6, x6, x2
    sll x7, x7, x1
    sll x8, x8, x2
    sll x9, x9, x1
    sll x10, x10, x2
    sll x11, x11, x1
    sll x12, x12, x2
    sll x13, x13, x1
    sll x14, x14, x2
    sll x15, x15, x1
    sll x16, x16, x2
    sll x17, x17, x1
    sll x18, x18, x2
    sll x19, x19, x1
    sll x20, x20, x2
    sll x21, x21, x1
    sll x22, x22, x2
    sll x23, x23, x1
    sll x24, x24, x2
    sll x25, x25, x1
    sll x26, x26, x2
    sll x27, x27, x1
    sll x28, x28, x2
    sll x29, x29, x1
    sll x30, x30, x2
    sll x31, x31, x1
