segre_test:
    li x1,  0xbeefbeef
    li x2,  0xbeefbeef
    li x3,  0xbeefbeef
    li x4,  0xbeefbeef
    li x5,  0xbeefbeef
    li x6,  0xbeefbeef
    li x7,  0xbeefbeef
    li x8,  0xbeefbeef
    li x9,  0xbeefbeef
    li x10, 0xbeefbeef
    li x11, 0xbeefbeef
    li x12, 0xbeefbeef
    li x13, 0xbeefbeef
    li x14, 0xbeefbeef
    li x15, 0xbeefbeef
    li x17, 0xbeefbeef
    li x18, 0xbeefbeef
    li x19, 0xbeefbeef
    li x20, 0xbeefbeef
    li x21, 0xbeefbeef
    li x22, 0xbeefbeef
    li x23, 0xbeefbeef
    li x24, 0xbeefbeef
    li x25, 0xbeefbeef
    li x26, 0xbeefbeef
    li x27, 0xbeefbeef
    li x28, 0xbeefbeef
    li x29, 0xbeefbeef
    li x30, 0xbeefbeef
    li x31, 0xbeefbeef
    sll x0, x1, 0xf1
    sll x2, x2, 0x10
    sll x3, x3, 0xf1
    sll x4, x4, 0x10
    sll x5, x5, 0xf1
    sll x6, x6, 0x10
    sll x7, x7, 0xf1
    sll x8, x8, 0x10
    sll x9, x9, 0xf1
    sll x10, x10, 0x10
    sll x11, x11, 0xf1
    sll x12, x12, 0x10
    sll x13, x13, 0xf1
    sll x14, x14, 0x10
    sll x15, x15, 0xf1
    sll x16, x16, 0x10
    sll x17, x17, 0xf1
    sll x18, x18, 0x10
    sll x19, x19, 0xf1
    sll x20, x20, 0x10
    sll x21, x21, 0xf1
    sll x22, x22, 0x10
    sll x23, x23, 0xf1
    sll x24, x24, 0x10
    sll x25, x25, 0xf1
    sll x26, x26, 0x10
    sll x27, x27, 0xf1
    sll x28, x28, 0x10
    sll x29, x29, 0xf1
    sll x30, x30, 0x10
    sll x31, x31, 0xf1
