segre_test:
    li x1,  -1
    li x2,  -2
    li x3,  -3
    li x4,  -4
    li x5,  -5
    li x6,  -6
    li x7,  -7
    li x8,  -8
    li x9,  -9
    li x10, -10
    li x11, -11
    li x12, -12
    li x13, -13
    li x14, -14
    li x15, -15
    li x16, -15
    li x17, -16
    li x18, -17
    li x19, -18
    li x20, -19
    li x21, -20
    li x22, -21
    li x23, -22
    li x24, -23
    li x25, -24
    li x26, -25
    li x27, -26
    li x28, -27
    li x29, -28
    li x30, -29
    li x31, -30
    slt x0, x1, -2
    slt x1, x3, -2
    slt x2, x3, -4
    slt x3, x5, -4
    slt x4, x6, -5
    slt x5, x5, -6
    slt x6, x7, -6
    slt x7, x6, -7
    slt x8, x8, -9
    slt x9, x9, -8
    slt x10, x11, -12
    slt x11, x13, -12
    slt x12, x13, -14
    slt x13, x15, -14
    slt x14, x16, -15
    slt x15, x15, -16
    slt x16, x17, -16
    slt x17, x16, -17
    slt x18, x18, -19
    slt x19, x19, -18
    slt x20, x21, -22
    slt x21, x23, -22
    slt x22, x23, -24
    slt x23, x25, -24
    slt x24, x26, -25
    slt x25, x25, -26
    slt x26, x27, -26
    slt x27, x26, -27
    slt x28, x28, -29
    slt x29, x29, -28
    slt x30, x30, -31
    slt x31, x31, -30
