segre_test:
    li x1,  0x20
    li x2,  0x10
    li x3,  0xcafecafe
    li x4,  0xcafecafe
    li x5,  0xcafecafe
    li x6,  0xcafecafe
    li x7,  0xcafecafe
    li x8,  0xcafecafe
    li x9,  0xcafecafe
    li x10, 0xcafecafe
    li x11, 0xcafecafe
    li x12, 0xcafecafe
    li x13, 0xcafecafe
    li x14, 0xcafecafe
    li x15, 0xcafecafe
    li x17, 0xcafecafe
    li x18, 0xcafecafe
    li x19, 0xcafecafe
    li x20, 0xcafecafe
    li x21, 0xcafecafe
    li x22, 0xcafecafe
    li x23, 0xcafecafe
    li x24, 0xcafecafe
    li x25, 0xcafecafe
    li x26, 0xcafecafe
    li x27, 0xcafecafe
    li x28, 0xcafecafe
    li x29, 0xcafecafe
    li x30, 0xcafecafe
    li x31, 0xcafecafe
    srl x0, x1, x1
    srl x2, x2, x2
    srl x3, x3, x1
    srl x4, x4, x2
    srl x5, x5, x1
    srl x6, x6, x2
    srl x7, x7, x1
    srl x8, x8, x2
    srl x9, x9, x1
    srl x10, x10, x2
    srl x11, x11, x1
    srl x12, x12, x2
    srl x13, x13, x1
    srl x14, x14, x2
    srl x15, x15, x1
    srl x16, x16, x2
    srl x17, x17, x1
    srl x18, x18, x2
    srl x19, x19, x1
    srl x20, x20, x2
    srl x21, x21, x1
    srl x22, x22, x2
    srl x23, x23, x1
    srl x24, x24, x2
    srl x25, x25, x1
    srl x26, x26, x2
    srl x27, x27, x1
    srl x28, x28, x2
    srl x29, x29, x1
    srl x30, x30, x2
    srl x31, x31, x1
